[package]
name = "rust-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.1"
bytes = "1.7.1"
prost-types = "0.13.1"

[build-dependencies]
anyhow = "1.0.86"
prost-build = { version="0.13.1" }
